services:
  app:
    build: .
    volumes:
      - ${PWD}:/home/app/
    ports:
      - "3000:3000"
      - "7000:7000"
    network_mode: "host"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    network_mode: "host"

networks:
  app-network:
